# Welcome to Jekyll!
#
# This config file contains settings that affect your entire site.

# Site settings
lang: en-US
title: "Ahtesham's Homepage"
description: "Bookmark this to keep an eye on my project updates!"
baseurl: "" # e.g. "/blog" if your repo is github.io/blog
url: "https://ahteshamibnemostafa.github.io" # change this to your GitHub Pages URL

author:
  name: "Ahtesham Ibne Mostafa"
  twitter:
  picture:

twitter_username:
github_username: ahteshamibnemostafa
logo:
search: false
search_full_content: false
search_provider:
algolia:
  application_id:
  index_name:
  search_only_api_key:
  powered_by: false

# Build settings
markdown: kramdown

# Use remote theme (fix for GitHub Pages)
remote_theme: "mmistakes/jekyll-theme-basically-basic"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

feed:
  path: atom.xml

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Exclusions
exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .editorconfig
  - .gitattributes
  - .jekyll-assets-cache
  - .sass-cache
  - .scss-lint.yml
  - CHANGELOG
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - Rakefile
  - README
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - /docs
  - /example

# Front Matter Defaults
defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
